import Providers from "./components/providers";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { IoIosNotifications } from "react-icons/io";
import { IoFilter } from "react-icons/io5";
import { IoMdSearch } from "react-icons/io";
import { FiRefreshCcw } from "react-icons/fi";

import "@rainbow-me/rainbowkit/styles.css";
import { ConnectButton } from "@rainbow-me/rainbowkit";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header className="w-full bg-[#9723c9] border-b-2 border-black py-6 flex items-center justify-between px-16">
            <h2 className="font-bold text-2xl text-white">Simple compound</h2>
            <div className="flex text-center items-center gap-4 ">
              <IoIosNotifications
                size={28}
                className="cursor-pointer text-white hover:text-black"
              />
              <ConnectButton />
            </div>
          </header>
          <div className="bg-[#E3DFF2] h-screen">
            <div className="py-8 px-16 w-screen">
              <div className="flex mb-8 justify-between">
                <button className="bg-[#A388EE] px-10 rounded-sm border-2 border-black font-semibold py-2 flex items-center gap-2 hover:text-white hover:border-white">
                  <IoFilter size={20} /> All Filters
                </button>

                <div className="flex items-center gap-8">
                  <button className="flex items-center gap-2 font-semibold">
                    <FiRefreshCcw size={24} className="hover:text-[#9723c9]" />
                  </button>

                  <button className="border-2 border-black rounded-sm bg-white px-24 py-2 self-end font-semibold flex items-center gap-2 hover:text-[#9723c9] hover:border-[#9723c9]">
                    <IoMdSearch size={20} /> Search
                  </button>
                </div>
              </div>

              {children}
            </div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
